### ISSUE TITLE
Issue building factories, Factory image missing?

### ISSUE THREAD

**Issue by Gageowe** [8BitToaster/Grand-Expansion#3]
Traceback (most recent call last):
  File "C:\Users\(my username)\Downloads\Grand-Expansion-master\Grand Expansion\game.py", line 1235, in <module>
    MainMenu(0)
  File "C:\Users\(my username)\Downloads\Grand-Expansion-master\Grand Expansion\game.py", line 635, in MainMenu
    game_loop()
  File "C:\Users\(my username)\Downloads\Grand-Expansion-master\Grand Expansion\game.py", line 1153, in game_loop
    draw(i * (640/width),j * (640/height) + 160,"Tile",board[j][i],height,width)
  File "C:\Users\(my username)\Downloads\Grand-Expansion-master\Grand Expansion\game.py", line 538, in draw
    gameDisplay.blit(Images["Factory"],(x,y))
KeyError: 'Factory'

This error appears similar to the issue I had with Cities

**Comment by Gageowe** [comment]
Iam having the same issue with fishermen too. I made an image for both the factory and the fisherman and  it works fine now.

**Comment by 8BitToaster** [comment]
I am very sorry this is happening to you. I have no idea why this bug is happening, but I have it on my list to try to fix. Is this because when you downloaded an updated game.py, it happened that you didn't download the updated images? I'll try to fix it, but it would be nice if you maybe checked that one thing. Sorry it keeps happening to you

-8BitToaster

**Comment by 8BitToaster** [comment]
Ok, the issue is fixed. I don't know how this bug is happening as some of the images in my folder aren't there even though I uploaded the factory image a long time ago. I'm sorry this kept happen, but now I checked and added Factory and Fisherman. This issue is fixed

-8BitToaster
